### ISSUE TITLE
Difference between SSD and CSD

### ISSUE THREAD

**Issue by 07hyx06** [KumapowerLIU/HeadArtist#1]
Hi, thanks for your insightful paper! 

After reading the paper, I find the proposed SSD technique quite similar to a concurrent work CSD (TEXT-TO-3D WITH CLASSIFIER SCORE DISTILLATION, ICLR2024). Is SSD identical to CSD or did I miss something?

Thanks in advance.

**Comment by KumapowerLIU** [comment]
Indeed, we find these two are very similar.  However, there are two differences between the SSD and CSD.  First, we introduce the SSD with the controlnet to make our model focus on head generation. Meanwhile, we find we the CSD does not use the CFG value, and we use the CFG=7.5 for texture and CFG=100 for geometry, respectively. We find the setting of these two CFG values is important to the quality of the final results. Especially for the geometry generation, we find the large CFG value can stable training since the normalmap is not the common image domain for the sd model.  We will add the discussion with CSD in the new version of our paper.
